// src/db/migrate.ts
//
// Run with: npm run db:migrate
// This applies any pending migration files (generated by
// `npm run db:generate`) to the actual database. Migrations are
// applied in order and Drizzle tracks which ones have already run
// in a special table, so re-running this is safe - it skips
// anything already applied.

import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import "dotenv/config";

const connectionString = process.env.DATABASE_URL!;

async function main() {
  // max: 1 because migrations should run as a single sequential
  // connection, not a pooled set - we don't want concurrent
  // migration attempts racing each other.
  const migrationClient = postgres(connectionString, { max: 1 });
  const db = drizzle(migrationClient);

  console.log("Running migrations...");
  await migrate(db, { migrationsFolder: "./src/db/migrations" });
  console.log("Migrations complete.");

  await migrationClient.end();
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
